pipeline:
  docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: docker.dartagnan.devops.fuse.tikal.io/tikalk/ghost
    registry: docker.dartagnan.devops.fuse.tikal.io
    tags:
      - 2.6.1.${DRONE_BUILD_NUMBER}
    # auto_tag: true

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    webhook: slack_webhook
    channel: dartagnan
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}

  helm_deploy:
    image: quay.io/ipedrazas/drone-helm
    secrets: [ api_server, kubernetes_token ]
    skip_tls_verify: true
    chart: ./helm/Chart.yaml
    update_dependencies: true
    values: image.tag=2.6.1.${DRONE_BUILD_NUMBER}
    values_files: [helm/values.yaml]
