pipeline:
  docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: docker.dartagnan.devops.fuse.tikal.io/tikalk/ghost
    registry: docker.dartagnan.devops.fuse.tikal.io
    tags:
      - 2.6.1.${DRONE_BUILD_NUMBER}
    # auto_tag: true

  helm_deploy:
    image: quay.io/ipedrazas/drone-helm
    secrets: [ api_server, kubernetes_token ]
    skip_tls_verify: true
    release: ${DRONE_BRANCH}
    chart: ./helm/Chart.yaml
    update_dependencies: true
    values: image.tag=2.6.1.${DRONE_BUILD_NUMBER}
    values_files: [helm/values.yaml]

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: dartagnan
    template: >
      {{#success build.status}}
        build {{build.number}} that took {{since build.started}} has succeeded. Good job. Ghost version 2.6.1.{{build.number}} was deployed. See build details: {{ build.link }}
      {{else}}
        build {{build.number}} that took {{since build.started}} has failed. Fix me please. See build details: {{ build.link }}
      {{/success}}
